### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by timshim** [carriera/fengshui-api#1]
This looks interesting though being more familiar with REST and never used a SOAP API before, I'm not sure how to use this? Is there an example of a URL structure to call the respective endpoints?

**Comment by carriera** [comment]
During next few days, we are planning to start new version of our platform which will allow you to use REST API.

**Comment by carriera** [comment]
Hi Again, Just want to inform you that according to our promise, REST API is ready. You can now try it.

**Comment by timshim** [comment]
Thank you. I will check it out.
